### ISSUE TITLE
Extension capabilities

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#44] opened 2017-12-12 00:42 UTC
We're seeing some _interesting_ use of extensions starting to be discussed, e.g.,:

* Overriding method semantics using a HTTP/2 setting (in the WebSockets draft)
* Referring to pseudo-headers as primary artefacts in HTTP header payloads (in the Signature proposal)

Some guidance about the relationship of version-specific syntax/extensions and "top-level" HTTP semantics would be helpful.

**Comment by mnot** [comment] 2020-05-25 00:32
I'm not sure what "h2 text in core" we're waiting for here; I think our goal for Semantics is to have as little version-specific text as possible. @mcmanus do you remember any more detail?

**Comment by royfielding** [comment] 2020-05-25 19:56
I think this is something we need to review for Versioning just prior to WGLC.

**Comment by MikeBishop** [comment] 2020-05-27 14:34
Looking at [the minutes of that meeting](https://github.com/httpwg/wg-materials/blob/gh-pages/ietf102/minutes.md#extension-capabilities-44), we had "an open issue to put text around the semantic issues around h/2," which I read as describing what an extension to a mapping (or perhaps the mapping itself, including its extensions) can and cannot modify about HTTP semantics.  That was presumably #50.

But then we closed #50 as a duplicate of this issue, so that's this issue again.  There was a PR for #50 which was closed by #342, which is already merged.  Presumably the text we were waiting for was in #342, and if it wasn't, we need to do it here.

**Comment by mnot** [comment] 2020-05-28 03:36
Perhaps we need to say that a version-specific extension (like SETTINGS or a frame type) can't override or modify the semantics of a version-independent mechanism or extension point (like a method or header) without explicitly being allowed by that protocol element (e.g., CONNECT does this implicitly, we should make it explicit).

**Comment by mnot** [comment] 2020-05-28 05:17
I think the above would go into a new section, "Extending HTTP", along with references to the various extension points.

That and "Protocol Versioning" (currently in 3. Conformance) might fit best in a new top-level section, "Versioning and Extending HTTP." Probably between Architecture and Conformance?

**Closed** 2020-07-13 05:38 UTC
Labels: has-proposal, semantics
